vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        post_logos:
            uri_prefix: /uploads/logos
            upload_destination: '%kernel.project_dir%/public/uploads/logos'
            namer: vich_uploader.namer_uniqid
        post_photos:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer: vich_uploader.namer_uniqid
        post_cv:
            uri_prefix: /uploads/cv
            upload_destination: '%kernel.project_dir%/public/uploads/cv'
            namer: vich_uploader.namer_uniqid
        post_screenshots:
            uri_prefix: /uploads/screenshots
            upload_destination: '%kernel.project_dir%/public/uploads/screenshots'
            namer: vich_uploader.namer_uniqid

            

